package ru.moneta.services_wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2022-06-15T22:49:25.316+03:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "MessagesService",
                  wsdlLocation = "https://moneta.ru/services.wsdl",
                  targetNamespace = "http://www.moneta.ru/services.wsdl")
public class MessagesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.moneta.ru/services.wsdl", "MessagesService");
    public final static QName MessagesSoap11 = new QName("http://www.moneta.ru/services.wsdl", "MessagesSoap11");
    static {
        URL url = null;
        try {
            url = new URL("https://moneta.ru/services.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MessagesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://moneta.ru/services.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MessagesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MessagesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessagesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MessagesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MessagesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MessagesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Messages
     */
    @WebEndpoint(name = "MessagesSoap11")
    public Messages getMessagesSoap11() {
        return super.getPort(MessagesSoap11, Messages.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Messages
     */
    @WebEndpoint(name = "MessagesSoap11")
    public Messages getMessagesSoap11(WebServiceFeature... features) {
        return super.getPort(MessagesSoap11, Messages.class, features);
    }

}
